language: node_js
language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: f524b4dd-b47d-4ab0-9330-fbec19c0b94d
  app: afternoon-falls-78211
  on:
    repo: DrewBlake/hotcold
